# Configurations
title:            Sorbonne IP Route Survey (IPRS)
longtitle:        Sorbonne IP Route Survey (IPRS)
author:           Dioptra Team
email:            admins@dioptra.io
description: >
  Sorbonne IPRS is an initiative to continuously monitor IP-level routing across the internet.

version:          1.0
gitbook_version:  3.2.3

url:              'https://sorbonne-iprs.github.io'
baseurl:          ''
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

search_enabled: false

# Aux links for the upper right navigation
#aux_links:
#  "Dioptra":
#    - "//dioptra.io"
#  "Iris":
#    - "//iris.dioptra.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

nav_enabled: true

heading_anchors: true

footer_content: "Copyright &copy; 2025 Sorbonne Universit√©. Distributed under the <a href=\"https://github.com/sorbonne-iprs/sorbonne-iprs.github.io/tree/main/LICENSE\">MIT license.</a>"

toc:
  enabled: true
  h_min:   1
  h_max:   3

logo: "/assets/images/just-the-docs.png"
favicon_ico: "/assets/images/favicon.ico"

# markdown render engine.
#markdown:         kramdown
#kramdown:
#  auto_ids:               true
#  input:                  GFM
#  math_engine:            mathjax
#  smart_quotes:           lsquo,rsquo,ldquo,rdquo
#  toc_levels:             1..6
#  syntax_highlighter:     rouge
#  syntax_highlighter_opts:
#    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

